baltimorecorps/hippo-backend

defaultcfg.py, scripts/init_localdb.sh, scripts/start_localdb.sh
FYI, @BayLadyCoder this will require you to restart the local database (because I changed what port it runs on), but should avoid the problem you had with the conflicting existing postgres database
=> Change db script to not conflict with existing postgres db

models/experience_model.py, resources/Experience.py, tests/test_api.py
Updates the experiences api to accept and return month and year for start and end dates.
=> Date picker update

tests/test_api.py
@widal001 Here's what a test looks like for the code you wrote, feel free to merge this once it makes sense
=> Add test for POSTing an experience date

models/experience_model.py, tests/test_api.py
Fix is for this card: https://trello.com/c/BWpc5X5T
=> Fix for "Degree not nullable in POST experience endpoint"

common/api_test_manual.txt, models/achievement_model.py, models/address_model.py, models/contact_model.py, models/email_model.py, models/experience_model.py, models/resume_item_model.py, models/resume_model.py, models/resume_section_model.py, models/tag_item_model.py, models/tag_model.py, tests/test_api.py
Adjusts the schema to EXCLUDE unknown values (such as fields that are dump_only) when loading  the request data.
=> Unknown field error

common/api_test_manual.txt, models/contact_model.py, resources/Contacts.py, tests/test_api.py
Hey @BayLadyCoder I'm creating a PR as a record but I might go ahead and merge this one which fixes the internal server error you encountered with the PUT request to contacts
=> Put contact bug

models/program_contact_model.py, tests/test_api.py
Adds `contact_id` to the data returned from the `api/contacts/<contact_id>/programs/<program_id>/ `and the `api/contacts/<contact_id>/programs/` endpoints
=> Program contact bug

models/contact_model.py, resources/Contacts.py, resources/ProgramContacts.py, tests/test_api.py
Updates the POST to `api/contacts/` endpoint to automatically create a program_contact record that connects the 'Place for Purpose' program to the newly created contact record
=> Create program contact

api.py, common/api_test_manual.txt, resources/FormAssembly.py
- Creates a TalentProgramApp class with a POST method in FormAssembly.py
- Adds that TalentProgramApp to the endpoint 
"/form-assembly/talent-app/"
=> Creates endpoint to process FA forms:

common/api_test_manual.txt, resources/FormAssembly.py, resources/Trello_Intake_Talent.py, resources/trello_utils.py
Merges most recent changes from FormAssembly talent branch:
- Moves intake talent card when form is submitted
- Updates program_contact record to stage 2
=> Form assembly talent

api.py, common/api_test_manual.txt, resources/FormAssembly.py, resources/Trello_Intake_Talent.py, resources/trello_utils.py
Reverts baltimorecorps/hippo-backend#64 because it undoes changes that we want to keep and fix with the next merge from form-assembly-talent
=> Revert "Master"

api.py, common/api_test_manual.txt, models/review_model.py, resources/Trello_Intake_Talent.py
Creates `ReviewTalentCard` endpoint which is called when a review is submitted from trello, triggering the following updates
- Updates the review record, setting the `is_active` field to `false` and the `score` field to the integer value associated with the reviewer decision on the card
- Archives the intake card associated with the review if the reviewer decision is "Not a Fit", otherwise moves the card to "Approved"
- Updates program contact record, setting `is_active` to 'false` if the reviewer decision is "Not a Fit", otherwise setting `stage=3`
Deployment considerations
- **DB Migrations:** None
- **Deployment Order:** N/A (independent of frontend)
- **Heroku Variables:** None
- **AuthZ/N Changes:** None
=> Form assembly review

api.py, app.py, auth.py, check_trello.py, models/contact_model.py, models/opportunity_app_model.py, models/opportunity_model.py, models/program_contact_model.py, requirements.txt, resources/FormAssembly.py, resources/Opportunity.py, resources/OpportunityApp.py, resources/ProgramContacts.py, resources/trello_utils.py, tests/conftest.py, tests/populate_db.py, tests/test_api.py, tests/trello_integration_test.py, trello_check.py
https://trello.com/c/9Lgb7GjY/46-opportunity-intake-flow
=> Opportunity intake - prep for launch

api.py, models/cycle_model.py, models/opportunity_model.py, models/program_contact_model.py, models/program_model.py, resources/FormAssembly.py, resources/OpportunityApp.py, resources/ProgramContacts.py, tests/populate_db.py, tests/test_api.py, tests/trello_integration_test.py
Merges `contact-eligibility` branch into staging branch `staff-post-opportunities` to resolve merge conflicts before merging with `master`
=> Contact eligibility

api.py, models/opportunity_model.py, resources/FormAssembly.py, resources/OpportunityApp.py, tests/populate_db.py, tests/test_api.py, tests/trello_integration_test.py
- Adds org_name to OpportunityIntake resource on the FormAssembly.py 
- Creates a new endpoint for `api/contacts/<contact_id>/app/` which returns a list of submitted applications associated with a given contact
=> Opportunity changes for ui

models/opportunity_app_model.py, models/resume_model.py, resources/Contacts.py, resources/OpportunityApp.py, tests/populate_db.py, tests/test_api.py
I threw this together really quick so feel free to adjust anything about the way it's set up, the design is not, like, really deeply thought through or anything (probably if you see something that could be done better, you are correct).
Also, noted that the pull request checklist we have set up is nice, but kind of a PITA to copy every time. See this to improve the flow:
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
**Heroku Variables**: N/A
**DB Migrations**: Yes
**Deployment Sequence**: Deploy backend before frontend
**Auth Changes**: N/A
=> Add a resume snapshot to opportunity app

api.py, models/contact_model.py, resources/Contacts.py, tests/test_api.py
Creates endpoint `GET api/contacts/short/` which returns the following request data:
```
[{first_name: str,
last_name: str,
id: int,
email: str},
{...}]
```
=> Feature get contact short

api.py, models/opportunity_app_model.py, resources/OpportunityApp.py, tests/test_api.py
- Creates endpoint `POST contacts/<contact_id>/opportunities/<opp_id>/interview` which changes the opportunity_app `status` to "interviewed"
- Creates endpoint `POST contacts/<contact_id>/opportunities/<opp_id>/make-offer/` which changes the opportunity_app `status` to "offer made"
- **Heroku Variables:**
- **DB Migrations:**
- **AuthZ/N Changes:**
- **Deployment Sequence:**
=> Feature employer app actions

api.py, models/opportunity_model.py, resources/Opportunity.py, tests/populate_db.py, tests/test_api.py
Creates endpoint `GET employer/opportunities/<opp_id>/` which returns the following data:
```
{"id": str,
"title": str,
"org_name": str,
"description": str,
"gdoc_link": str,
"recommended_apps": [{
"id": str,
"contact": {
"email": str,
},
"is_active": bool
}]}
```
=> Feature employer app view

api.py, models/opportunity_app_model.py, models/opportunity_model.py, resources/OpportunityApp.py, tests/test_api.py
- Changes offer_made to considered_for_role and changes "make-offer" to 
"consider" in the endpoint
- Adds interview_date and interview_time to OpportunityApp model and 
creates a hybrid property interview_completed which indicates whether or 
not the interview date and time have passed
- Sets interview_date and interview_time when POST 
contacts/<contact_id>/app/<opp_id>/interview
=> Modifies actions that an employer can do:

models/achievement_model.py, models/experience_model.py
Remove the limits on fields on experience and achievement tables:
- Host
- Title
- Link
- Description
- **Heroku Variable:** No
- **AuthZ/N changes:** No
- **Deployment sequence:** Independent of frontend
=> Bug exp character limit

models/achievement_model.py, models/experience_model.py
- Host
- Title
- Link
- Description
- **Heroku Variables:** No
- **DB migrations:** Yes
- **AuthZ/N Changes:** No
- **Deployment Sequence:** Independent of frontend
=> Remove the limits on fields on experience and achievement tables:

models/opportunity_model.py, tests/populate_db.py, tests/test_api.py
Adds program_name column to opportunity table
Deployment considerations:
Heroku Variables: No
DB migrations: Yes
AuthN/Z Changes: No
Deployment sequence: Backend before frontend
=> Add program_name to Opportunity table

api.py, resources/Opportunity.py, tests/test_api.py
Creates an endpoint for staff to activate roles
=> added an endpoint for activating an opportunity

resources/Contacts.py, tests/trello_integration_test.py
Updates `POST api/contacts/` to prevent duplicate contacts from being created
=> Bug duplicate contacts

models/contact_model.py, tests/populate_db.py
Fixes bug with deleting contacts that had an active user session by cascading the delete to the user sessions related to the contact being deleted
=> Adds test for deleting user session along with the contact

api.py, models/contact_model.py, models/program_contact_model.py, models/program_model.py, resources/Contacts.py, tests/test_api.py
Creates endpoint `GET api/contacts/programs` which returns a list of contacts and the programs that they are interested in or approved for
=> Staging internal app endpoints

api.py, models/contact_model.py, models/program_contact_model.py, models/program_model.py, resources/Contacts.py, tests/test_api.py
Also removes cycle and reviews from the program schema
=> Creates endpoint for `api/contacts/programs` 

api.py, models/contact_model.py, models/program_contact_model.py, models/program_model.py, resources/Contacts.py, tests/populate_db.py, tests/test_api.py, tests/trello_integration_test.py
Adds optional query parameter to filter contacts/programs by is_approved
=> Staging contact programs approved

resources/Contacts.py, tests/populate_db.py, tests/test_api.py
Adds `is_approved` query parameter to allow filtering candidates by approved status
=> Adds optional query parameter to filter contacts/programs by is_approved

api.py, models/contact_model.py, models/profile_model.py, models/program_app_model.py, models/program_model.py, resources/Profile.py, resources/ProgramApp.py, tests/populate_db.py, tests/test_api.py
Creates tables and endpoints for program apps:
- Creates `program_app` table
- Fixes spelling mistake with `hawaiian` field on `race` table
- Creates `GET api/contacts/<contact_id>/program-apps/` to retrieve list of program apps associated with a contact
- Creates `GET api/contacts/<contact_id>/program-apps/interested` to add the list of interested programs
Deployment Considerations:
- Migration: Yes
- AuthZ/N Changes: No
- Deployment Sequence: Backend before frontend
=> Feature program app tables

models/contact_model.py, models/profile_model.py, models/program_app_model.py, resources/Contacts.py, resources/Profile.py, resources/ProgramApp.py, tests/populate_db.py, tests/test_api.py, tests/trello_integration_test.py
- Adds `programs_completed` table for profile endpoint
- Adds `value_question1` and `value_question2` to profile table
- Adds `hear_about_us` and `hear_about_us_other` to profile table
- Adds `needs_help_programs` to profile table
- Fixes bug with `PUT contacts/<contact_id>/program-apps/interested`
- Changes `date_approved` to `decision_date` on `program_app` table
- Creates profile record when calling `POST contacts`
Deployment Considerations:
- DB Migrations: Yes
- AuthN/Z Changes: No
- Deployment Sequence: Backend before frontend
=> Cleans up remaining items on about-me:

models/contact_model.py, resources/Contacts.py, resources/Profile.py, tests/test_api.py
- updates `email_primary` as well as `email` when calling `PUT api/contacts/<contact_id>/about-me`
- Adds `profile` to `GET api/contacts/<contact_id>/`
=> Bug put about me email

api.py, resources/Program.py, tests/test_api.py
Returns a list of the active programs in the db
=> Adds `GET api/programs` endpoint

api.py, change-sets/refactoring.md, migrate_skills_to_capabilities.py, models/old_skill_model.py, models/program_contact_model.py, models/resume_item_model.py, models/resume_model.py, models/resume_section_model.py, models/tag_item_model.py, models/tag_model.py, models/templates_model.py, resources/Achievement.py, resources/ProgramContacts.py, resources/Resume.py, resources/Tag.py
This branch refactors the code base, beginning with tests
Moves test data out of `test_api.py` and populates the db using that test data rather than through explicit init statements in `populate_db.py`
- Removes everything but `POSTS` and `CONTACTS` from `test_api.py`
- Creates a `tests/data/` folder with a file for each group of related resources
Adds `# TODO: DELETE THIS` comments next to each of the sections of code that can be removed
- Adds comments to following endpoints:
- `/tags/`
- `/tags/<int:tag_id>`
- `/contacts/<int:contact_id>/tags/`
- `/contacts/<int:contact_id>/tags/<int:tag_id>`
- `/contacts/<int:contact_id>/achievements/`
- `/contacts/<int:contact_id>/resumes/`
- `/resumes/<int:resume_id>/`
- `/resumes/<int:resume_id>/sections/`
- …
=> Feature code removal notes
