resources/trello_utils.py

In a previous commit I changed board.cards from a list to a dictionary 
keyed by card.id but the find_card_by_custom_field() expects a list of 
cards not a dictionary. This commit fixes that bug by replacing 
self.cards with self.cards.val() in the method

Fixes bug that was breaking POST to contacts:

---

models/contact_model.py
tests/test_api.py

Merges changes from contact-put-bug which sets the `programs` field in the `ContactSchema` to `dump_only=True` so that it is excluded from the PUT request to `api/contacts/`

Contact put bug

---

app.py
auth.py
resources/Achievement.py
resources/Contacts.py
resources/Experience.py
resources/ProgramContacts.py
resources/Resume.py
resources/Skills.py
resources/Tag.py
tests/conftest.py

This update is the one that actually locks down our API (replaces the "privacy screen" level of security we've had so far with an actual locked door)
It adds a requirement that a user is logged in to nearly all the endpoints, and also checks if they are authorized to see this. It allows for staff users, who can see all users (but not edit their information). The `is_authorized_*` functions are the key to all this, as you can see in the code.
The other key here is the sessions functionality, which relays the information about whether or not the user is logged in, as well as keeping track of their permissions for the session.
This pull request on the frontend needs to be deployed before this PR to avoid breaking everything, because it modifies the frontend to send cookies on every request: …

Add Authorization (AuthZ) to endpoints

---

api.py
models/cycle_model.py
models/opportunity_model.py
models/program_contact_model.py
models/program_model.py
resources/FormAssembly.py
resources/Opportunity.py
resources/OpportunityApp.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py

Merges the following branches into master:
- `opportunity-changes-for-ui`
- `contact-eligibility`
- `add-gdoc-link-to-opps`
Which does the following:
- Adds `gdoc_link`, `cycle_id`, and `org_name` to opportunity table
- Adds 'gdoc_link`, `cycle_id`, `org_name`, and `program_id` to opportunity schema
- Creates `contacts/<contact_id>/app/` which returns a list of applications associated with a given contact (used by the frontend to check the whether the contact has applied to the available opportunities)
Deployment considerations:
- **Deployment sequence:** Backend before frontend
- **AuthZ/AuthN Changes:** N/A

Staff post opportunities

---

models/opportunity_model.py
resources/FormAssembly.py
tests/populate_db.py
tests/test_api.py

Merges add-gdoc-link-to-opps feature branch to master for deployment:
- Adds `gdoc_link` to opportunity table and schema as a required column/field
- Makes 'gdoc_id` nullable in the table and optional in the schema
- Makes 'card_id` nullable in the table and optional in the schema
- **Deployment sequence:** Backend before frontend
- **AuthN/AuthZ Changes:** N/A

Add gdoc link to opps

---

api.py
models/cycle_model.py
models/opportunity_model.py
models/program_contact_model.py
models/program_model.py
resources/FormAssembly.py
resources/OpportunityApp.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py
tests/trello_integration_test.py

Merges contact-eligibility into master for deployment, which does the following: 
- Adds `cycle_id` to opportunity table
- Adds `cycle_id` and `program_id` to opportunity schema
- Sets `cycle_id` in the POST method of the OpportunityIntake resource
- Removes responses from the program_contact schema
- Removes questions from the program schema
- **Deployment Sequence:** Deploy backend before frontend
- **Auth Changes:** N/A

Contact eligibility

---

models/opportunity_app_model.py
models/resume_model.py
resources/Contacts.py
resources/OpportunityApp.py
tests/populate_db.py
tests/test_api.py

Merges `resume-snapshot` into `applicants-express-interest` feature set branch:
- Creates `resume_snapshot` table with `id` and `resume` columns, which stores a text serialized version of the json data needed to populate the resume in the frontend
- When updating the `opportunity_app` record, creates a step to check for resume data and if it exists, it creates a new `resume_snapshot` record and relates it to the `opportunity_app` record
Considerations for deployment: 
- **DB Migration:** Yes
- **Deployment Sequence:**  Backend before frontend

Resume snapshot

---

api.py
resources/OpportunityApp.py
tests/test_api.py

Merges `feature-staff-reopen-app` to `dev` adding the following functionality:
- Creates endpoint `POST api/contacts/<contact_id>/app/<opportunity_id>/reopen/` which changes the stage of the `opportunity_application` back to "draft"
Considerations for deployment: 
- **AuthN/Z Changes:** New permission `write:app`

Feature staff reopen app

---

api.py
models/opportunity_app_model.py
resources/OpportunityApp.py
tests/test_api.py

Merges `feature-staff-recommend-app` to `staging-staff-recommend-applicants` adding the following functionality:
- Creates endpoint `POST api/contacts/<contact_id>/app/<opportunity_id>/recommend/` which changes the stage of the `opportunity_application` to "recommended"
Considerations for deployment: 
- **AuthN/Z Changes:** New permission `write:app`

Feature staff recommend app

---

api.py
models/opportunity_app_model.py
models/opportunity_model.py
requirements.txt
resources/Opportunity.py
resources/OpportunityApp.py
tests/test_api.py

Merges the feature branch `staff-opportunity-view` into `staging-staff-recommend-applicants` which adds the following functionality:
- Creates a new endpoint `GET api/internal/opportunities/` which returns a list of opportunities and the applications associated with them
Deployment considerations:
- **AuthZ/N Changes:** New permission `view:internal-opportunity`

Staff opportunity view

---

resources/OpportunityApp.py
tests/test_api.py

Instead of returning 404 when a contact hasn't applied for anything, it 
instead returns 200 and an empty list "[]"

Changes tests to fix 404 bug with GET contacts/<id>/app/:

---

api.py
models/opportunity_app_model.py
resources/OpportunityApp.py
tests/test_api.py

Creates endpoint `POST api/contacts/<contact_id>/app/<opp_id>/not-a-fit/` which sets the `is_active` field on the opportunity_app record to `false`
- **AuthZ/N Changes:** new staff permission `write:app`

Feature staff reject app

---

api.py
models/opportunity_app_model.py
models/opportunity_model.py
requirements.txt
resources/Opportunity.py
resources/OpportunityApp.py
tests/test_api.py

Changes:
- Creates endpoint `GET api/internal/opportunities/` which returns a list of opportunities and their related applications
- Creates endpoint `POST api/contacts/<contact_id>/app/<opp_id>/recommend/` which sets the status of the opportunity app record to 'recommended'
- Creates endpoint `POST api/contacts/<contact_id>/app/<opp_id>/reopen/` which resets the status of the opportunity app record to 'draft'
- Creates endpoint `POST api/contacts/<contact_id>/app/<opp_id>/not-a-fit/` which sets `is_active=false` on the opportunity app record
- Fixes the bug with the status code when calling `GET api/contacts/<contact_id>/app/`
- **AuthZ/N Changes:** create new permission `write:app`
- **Deployment …

Staging staff recommend applicants

---

api.py
models/contact_model.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py

Creates endpoint to approve a contact for matching: `POST api/programs/<program_id>/contacts/approve-many/` which expects the payload:
```
[{"id": <int: contact_id>,
"first_name": <str: first_name>,
"last_name": <str: last_name>,
"email": <str: email>},
{...}]
```
- **AuthZ/N Changes:**  Uses permission `write:all-users`

Feature program contact approve

---

api.py
models/opportunity_app_model.py
models/opportunity_model.py
models/program_contact_model.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py

Creates endpoint `GET api/internal/applications/?program_id=<program_id>` which returns a list of applicants and the opportunities they've applied for with the following format
```
{"id": int,
"is_approved": bool,
"stage": int,
"contact": {
"id": int,
"email": str
},
"applications": [{
"id": str,
"opportunity": {
"id": str,
"title": str,
"org_name": str
}
}]}
```
- **AuthZ/N Changes:** Creates permission `view: internal-applications`

Feature get internal applications

---

models/contact_model.py
resources/Contacts.py
resources/ProgramContacts.py
tests/test_api.py

Fixes a design bug in the feature-program-contact-approve branch, which returned an error when a contact included in the payload didn't have an existing program_contact, also removed an error thrown if a contact included in the payload has already been approved.

Bug program contact approve

---

api.py
models/contact_model.py
models/opportunity_app_model.py
models/opportunity_model.py
models/program_contact_model.py
resources/Contacts.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py

Backend changes:
- Creates endpoint `GET api/contacts/short/` which returns a list of all contacts with a lightweight format: 
```
[{first_name: str,
last_name: str,
id: int,
email: str},
{...}]
```
- Creates endpoint `GET api/internal/applications/?program_id=<program_id>` which returns a list of applicants and the opportunities they've applied for with the following format
```
{"id": int,
"is_approved": bool,
"stage": int,
"contact": {
"id": int,
"email": str
},
"applications": [{
"id": str,
"is_active": bool,
"opportunity": {
"id": str,
"title": str,
"org_name": str
}
}]}
```
- Creates endpoint to approve a contact for matching: `POST api/programs/<program_id>/contacts/approve-many/` which expects the payload:
```
[{"id": <int: …
```

Staging staff internal candidate view

---

api.py
models/opportunity_app_model.py
resources/OpportunityApp.py
tests/test_api.py

- Creates endpoint `POST contacts/<contact_id>/opportunities/<opp_id>/interview` which changes the opportunity_app `status` to "interviewed"
- Creates endpoint `POST contacts/<contact_id>/opportunities/<opp_id>/make-offer/` which changes the opportunity_app `status` to "offer made"
- **Heroku Variables:**
- **DB Migrations:**
- **AuthZ/N Changes:**
- **Deployment Sequence:**

Feature employer app actions

---

resources/ProgramContacts.py
tests/test_api.py

Returns the following response data when `POST programs/<program_id>/contacts/approve-many/` is called:
```
[{"id": int,
"is_approved": bool,
"stage": int,
"contact": {
"id": int,
"email": str
},
"applications": [{
"id": str,
"is_active": bool,
"opportunity": {
"id": str,
"title": str,
"org_name": str
}
}]},
{...}]
```
- **Deployment Sequence:** N/A

Bug reapprove program contact

---

api.py
models/opportunity_app_model.py
models/opportunity_model.py
resources/Opportunity.py
resources/OpportunityApp.py
resources/ProgramContacts.py
tests/populate_db.py
tests/test_api.py

Backend changes:
- Creates endpoint `GET org/opportunities/<opp_id>/` which returns the following data:
```
{"id": str,
"title": str,
"org_name": str,
"description": str,
"gdoc_link": str,
"applications": [{
"id": str,
"contact": {
"email": str,
},
"is_active": bool,
"interview_date": date,
"interview_time": str with format 12:01 PM,
"interview_completed": bool
}]}
```
- Creates endpoint `POST contacts/<contact_id>/opportunities/<opp_id>/interview` which changes the opportunity_app `status` to "interviewed" and sets `interview_date` and `interview_time` with the following payload expected:
```
{"interview_date": date,
"interview_time": str with format "12:01 PM"}
```
- Creates endpoint `POST …

Staging employer view applicants

---

resources/FormAssembly.py
tests/trello_integration_test.py

Preserves  the existing labels on the card when a talent application form is submitted and new labels are applied

Bug preserve card labels on submit

---

resources/FormAssembly.py
tests/trello_integration_test.py

Returns `400` and the following error message: `Application has already been submitted` if the trello card associated with an application is already past the "submitted" list on the trello board

Adds error message if trying to resubmit an app

---

models/opportunity_model.py
tests/test_api.py

Adds field `is_active` to the `opportunity` model and schema
- **AuthN/Z Changes:** No

Adds field is_active to the opportunity model and schema

---

models/opportunity_model.py
tests/test_api.py

Adds field `is_active` to the `opportunity` model and schema
- **AuthN/Z Changes:** No

Staging hide inactive opportunities

---

models/achievement_model.py
models/experience_model.py
resources/FormAssembly.py
tests/trello_integration_test.py

Adds the following patches to existing bugs:
- Preserves existing labels on the card when an application is submitted
- Checks to see whether an application has already been submitted, and if so returns a `400` status code and an error message when trying to resubmit

Staging trello bug fixes

---

models/contact_model.py
tests/populate_db.py

Fixes bug with `DELETE api/contacts/<contact_id>/` which prevented deleting a user that had an active `user_session` record

Adds test for deleting user session along with the contact

---

models/profile_model.py
tests/test_api.py

Fixes bug with `PUT contacts/<contact_id>/about-me` which didn't allow the `programs_completed` field to be null in the payload

Bug programs completed nullable

---

api.py
change-sets/code-removal.md
change-sets/filter-skills.md
tests/test_api.py

Removes sections of the code that are no longer in use
Removes endpoints from api.py and the tests that reference those endpoints in test_api.py
- Removes the following endpoints:
- `/tags/`
- `/tags/<int:tag_id>`
- `/contacts/<int:contact_id>/tags/`
- `/contacts/<int:contact_id>/tags/<int:tag_id>`
- `/contacts/<int:contact_id>/achievements/`
- `/contacts/<int:contact_id>/resumes/`
- `/resumes/<int:resume_id>/`
- `/resumes/<int:resume_id>/sections/`
- `/resumes/<int:resume_id>/sections/<int:section_id>`
- `/contacts/<int:contact_id>/generate-resume/`
- `/contacts/<int:contact_id>/programs`
- `/contacts/<int:contact_id>/programs/<int:program_id>`
- `/programs/<int:program_id>/contacts/approve-many`
- Removes the following tests:
- `test_put()` for `api/contacts/123/programs/1/`
- …

Feature endpoint removal
